config/routes.rb
require 'sidekiq/web'

Rails.application.routes.draw do

  authenticate :user, lambda { |u| u.admin? } do
    mount Sidekiq::Web => '/sidekiq'
  end
  
  use_doorkeeper
  devise_for :users, controllers: { omniauth_callbacks: 'omniauth_callbacks' }
  devise_scope :user do
    post '/finish_sign_up' => 'omniauth_callbacks#finish_sign_up'
  end
  
  root to: "questions#index"

  get 'search', to: 'search#index'

  concern :votable do
    member do
      post :vote_up
      post :vote_down
      post :vote_cancel
    end
  end

  namespace :api do
    namespace :v1 do
      resources :profiles, only: :index do
        get :me, on: :collection
      end
      resources :questions, shallow: true do
        resources :answers
      end
    end
  end

  resources :questions, concerns: :votable do
    resources :comments, only: :create, defaults: { commentable: 'questions' }
    post :subscribe, on: :member
    post :unsubscribe, on: :member
    resources :answers , shallow: true , concerns: :votable do
      
      resources :comments, only: :create, defaults: { commentable: 'answers' }
    end
  end

  resources :attachments, only: :destroy
  patch "/answers/best_answer/:id", to: 'answers#best_answer', as: 'best_answer'

end

app/models/question.rb
class Question < ActiveRecord::Base
  include Votable
  include Attachable
  include Commentable
  belongs_to :user
  has_many :answers, dependent: :destroy
  has_many :subscriptions, dependent: :destroy
  has_many :subscribers, through: :subscriptions
  validates :title, presence: true, length: { in: 15..150 }
  validates :body, presence: true, length: { in: 30..30000 }
  validates :user_id, presence: true

  scope :yesterday, -> { where(created_at: Time.zone.yesterday.to_time.all_day) }

  after_create :subscribe_author

  def subscribe(user)
    self.subscribers << user unless subscribed?(user)
  end

  def unsubscribe(user)
    self.subscribers.delete(user) if subscribed?(user)
  end

  def subscribed?(user)
    subscribers.include?(user)
  end

  private

  def subscribe_author
    subscribe(user)
  end
end

app/controllers/api/v1/questions_controller.rb
class Api::V1::QuestionsController < Api::V1::BaseController
  before_action :load_question, only: [ :show ]

  authorize_resource


  def index 
    respond_with(@questions = Question.all)
  end

  def show
   respond_with @question, serializer: QuestionPreviewSerializer
  end

  def create
    respond_with(@question = current_resource_owner.questions.create(question_params))
  end
   
  private

  def load_question
    @question = Question.find(params[:id])
  end
   
  def question_params
    params.require(:question).permit(:title, :body)
  end

end

app/controllers/questions_controller.rb
class QuestionsController < ApplicationController
  include Voted
  before_action :authenticate_user!, only: [ :new, :create ]
  before_action :load_question, only: [:show, :update, :destroy, :subscribe, :unsubscribe]
  before_action :build_answer, only: [:show]
  after_action :question_pub, only: [:create]
  respond_to :js, only: :update
  authorize_resource
  def index
  	respond_with(@questions = Question.all)
  end

  def show
    respond_with(@question)
  end

  def new
  	respond_with(@question = Question.new) 
  end


  def create
    respond_with(@question = current_user.questions.create(question_params))
  end

  def update
    @question.update(question_params) 
    respond_with(@question)
  end
  
  def destroy
    @question.destroy 
    respond_with(@question)
  end
  
  def subscribe
    @question.subscribe(current_user)
    redirect_to @question, notice: 'Subscribed successfully!'
  end

  def unsubscribe
    @question.unsubscribe(current_user)
    redirect_to @question, notice: 'Unsubscribed successfully!'
  end

  private
    
    def load_question
      @question = Question.find(params[:id])
    end

    def build_answer
      @answer = @question.answers.build
    end

    def question_pub
      PrivatePub.publish_to "/questions", question: @question.to_json if @question.valid?
    end

    def question_params
      params.require(:question).permit(:title, :body, attachments_attributes: [:id, :file, :_destroy])
    end
end

app/helpers/questions_helper.rb
module QuestionsHelper
end

app/views/questions/_form.html.slim
= form_for @question do |f|
  p= f.label :title
  p= f.text_field :title
  p= f.label :body
  p= f.text_area :body
  p Attachments:
  p
    = f.fields_for :attachments, @question.attachments.build do |attachment|
      = render 'attachments/fields', f: attachment
    .links
      = link_to_add_association 'Add Attachment', f, :attachments, 
      partial: 'attachments/fields'
  p= f.submit 'Create'

app/views/questions/_question.html.slim
- cache_unless user_signed_in?, @question do
  div id="question-#{ @question.id }" class="question"
    h3 Title:
    p= @question.title
    h3 Body:
    p= @question.body
    p Attachments:
    ul
      - @question.attachments.each do |a|
        = render 'attachments/attachment', attachment: a
    h4 Comments:
    .question_comments
      ul
        = render @question.comments
    .question_comment_form
      = render 'comments/form', commentable: @question
    h3 Rating for Question:
    .question_votes
      = render 'votes/score', votable: @question
    .question_votesbuttons
      = render 'votes/buttons', votable: @question
  

    p= link_to 'Back', questions_path
    p
      - if can?(:be_subscribed, @question)
        - if @question.subscribed?(current_user)
          = link_to 'Unsubscribe', unsubscribe_question_path(@question), method: :post
        - else
          = link_to 'Subscribe', subscribe_question_path(@question), method: :post
    - if can?(:modify, @question)
      p= link_to 'Delete Question', question_path(@question, :authenticity_token => form_authenticity_token()), method: :delete, data: { confirm: 'Are You sure?' }
      p= link_to 'Edit Question', '', class: 'edit-question-link', data: { question_id: @question.id }
      p
        = form_for @question, remote: true, html: { id: "edit_question_#{@question.id}" }  do |f|
          .question-edit-errors
          = f.label :title, "Edit Title"
          p= f.text_field :title
          = f.label :body, "Edit Body"
          p= f.text_area :body
          p Attachments:
          p
            .links
              = link_to_add_association 'Add Attachment', f, :attachments, 
              partial: 'attachments/fields'
          p= f.submit 'Save'
= subscribe_to "/comments"

app/views/questions/index.html.slim
h1 All Questions
- cache_unless user_signed_in?, collection_cache_key_for(Question) do
  - if can?(:create, Question)
    p = link_to 'Ask Question', new_question_path
  .questions_list
    ul
      - @questions.each do |question|
        li= link_to question.title, question

= subscribe_to "/questions"

app/views/questions/new.html.slim
== render 'form'

app/views/questions/show.html.slim
h2 Question
= render 'question'

h3 Answers
.answers data={ question_id: "#{@question.id}"}
  = render @question.answers
= render 'answers/form'

= subscribe_to "/questions/#{@question.id}/answers"

app/views/questions/update.js.erb
<% if @question.errors.present? %>
  <% @question.errors.full_messages.each do |message| %>
    $('.question-edit-errors').append('<ul><li><%= j message %></li></ul>');
  <% end %>
<% else %>
  <% if remotipart_submitted? %>
    $('<%= "#question-#{ @question.id }" %>').replaceWith('<%= j "#{render partial: "question"}" %>');
  <% else %>
    $('<%= "#question-#{ @question.id }" %>').replaceWith('<%= j render partial: "question" %>');
  <% end %> 
  $('.question-edit-errors').empty();
<% end %>