config/routes.rb
require 'sidekiq/web'

Rails.application.routes.draw do

  authenticate :user, lambda { |u| u.admin? } do
    mount Sidekiq::Web => '/sidekiq'
  end
  
  use_doorkeeper
  devise_for :users, controllers: { omniauth_callbacks: 'omniauth_callbacks' }
  devise_scope :user do
    post '/finish_sign_up' => 'omniauth_callbacks#finish_sign_up'
  end
  
  root to: "questions#index"

  get 'search', to: 'search#index'

  concern :votable do
    member do
      post :vote_up
      post :vote_down
      post :vote_cancel
    end
  end

  namespace :api do
    namespace :v1 do
      resources :profiles, only: :index do
        get :me, on: :collection
      end
      resources :questions, shallow: true do
        resources :answers
      end
    end
  end

  resources :questions, concerns: :votable do
    resources :comments, only: :create, defaults: { commentable: 'questions' }
    post :subscribe, on: :member
    post :unsubscribe, on: :member
    resources :answers , shallow: true , concerns: :votable do
      
      resources :comments, only: :create, defaults: { commentable: 'answers' }
    end
  end

  resources :attachments, only: :destroy
  patch "/answers/best_answer/:id", to: 'answers#best_answer', as: 'best_answer'

end

app/models/attachment.rb
class Attachment < ActiveRecord::Base
  belongs_to :attachable, polymorphic: true, touch: true
  validates :file, presence: true
  mount_uploader :file, FileUploader
  delegate :url, to: :file
  
end

app/controllers/attachments_controller.rb
class AttachmentsController < ApplicationController
  before_action :authenticate_user!
  before_action :load_attachment, only: [:destroy]

  authorize_resource

  def destroy
    @attachment.destroy 
  end

  private

  def load_attachment
    @attachment = Attachment.find(params[:id])
end
end

app/helpers/attachments_helper.rb
module AttachmentsHelper
end

app/views/attachments/_attachment.html.slim
div id="attachment-#{ attachment.id }"
  li
    = link_to attachment.file.identifier, attachment.file.url
    - if can?(:destroy, attachment)
      |&nbsp;
      = link_to 'Delete File', attachment_path(attachment), method: :delete, remote: true

app/views/attachments/_fields.html.slim
.nested-fields
  = f.label :file
  br
  = f.file_field :file
  .links
    = link_to_remove_association "Remove Attachment", f

app/views/attachments/destroy.js.erb
<% if @attachment.destroyed? %>
  $('.notice').append("<p >Your file was deleted </p>")
  $( '<%= "#attachment-#{ @attachment.id }" %>' ).remove();
<% else %>
  $('.notice').append("<p >Your can't delete file </p>")
<% end %>