config/routes.rb
require 'sidekiq/web'

Rails.application.routes.draw do

  authenticate :user, lambda { |u| u.admin? } do
    mount Sidekiq::Web => '/sidekiq'
  end
  
  use_doorkeeper
  devise_for :users, controllers: { omniauth_callbacks: 'omniauth_callbacks' }
  devise_scope :user do
    post '/finish_sign_up' => 'omniauth_callbacks#finish_sign_up'
  end
  
  root to: "questions#index"

  get 'search', to: 'search#index'

  concern :votable do
    member do
      post :vote_up
      post :vote_down
      post :vote_cancel
    end
  end

  namespace :api do
    namespace :v1 do
      resources :profiles, only: :index do
        get :me, on: :collection
      end
      resources :questions, shallow: true do
        resources :answers
      end
    end
  end

  resources :questions, concerns: :votable do
    resources :comments, only: :create, defaults: { commentable: 'questions' }
    post :subscribe, on: :member
    post :unsubscribe, on: :member
    resources :answers , shallow: true , concerns: :votable do
      
      resources :comments, only: :create, defaults: { commentable: 'answers' }
    end
  end

  resources :attachments, only: :destroy
  patch "/answers/best_answer/:id", to: 'answers#best_answer', as: 'best_answer'

end

app/models/answer.rb
class Answer < ActiveRecord::Base
  include Votable
  include Attachable
  include Commentable
  default_scope { order(best: :desc) }

  belongs_to :question, touch: true
  belongs_to :user
  validates :body, presence: true, length: { in: 30..30000 }
  validates :question, presence: true
  
  after_commit :sent_notice, on: :create

  def set_best!
    transaction do
      question.answers.update_all(best: false, updated_at: Time.now)
      self.update!(best: true)
    end
  end

  private
    def sent_notice
      NewAnswerNoticeJob.perform_now(self)
  end
end

app/controllers/answers_controller.rb
class AnswersController < ApplicationController
  include Voted
  before_action :authenticate_user!, only: [ :create, :update, :destroy ] 
  before_action :set_question, only: [ :create ]
  before_action :set_answer, only: [ :update, :destroy, :best_answer ]
  
  respond_to :js
  
  authorize_resource

  def create
   respond_with(@answer = @question.answers.create(answer_params.merge(user: current_user)))
  end
  
  def update
    @answer.update(answer_params) 
    respond_with @answer
  end

  def best_answer
    @answer.set_best! 
    respond_with @answer
  end

  def destroy
    @answer.destroy 
    respond_with @answer
  end

  private
  
  def set_question
    @question = Question.find(params[:question_id])
  end


  def set_answer
    @answer = Answer.find(params[:id])
    @question = @answer.question
  end
  

  def answer_params
    params.require(:answer).permit(:body, attachments_attributes: [:id, :file, :_destroy])
  end
end

app/controllers/api/v1/answers_controller.rb
class Api::V1::AnswersController < Api::V1::BaseController
  before_action :set_question, only: [ :index, :create ]
  before_action :set_answer, only: [ :show ]
  
  authorize_resource

  def index
  	@answers = @question.answers
    respond_with @answers 
  end
  
  def show
    respond_with @answer, serializer: AnswerPreviewSerializer 
  end

  def create
    respond_with(@answer = @question.answers.create(answer_params.merge(user: current_resource_owner)))
  end
  
  private

  def answer_params
    params.require(:answer).permit(:body)
  end

  def set_answer
    @answer = Answer.find(params[:id])
  end

  def set_question
    @question = Question.find(params[:question_id])
  end

end

app/helpers/answers_helper.rb
module AnswersHelper
end

app/views/answers/_answer.html.slim
- cache_unless user_signed_in?, answer do
  div id="answer-#{ answer.id }" class="answer" 
    .answer_body 
      - if answer.persisted?
        - if answer.best?
          p Best Answer
        p
          = answer.body
        h4 Attachments:
        ul
          - answer.attachments.each do |a|
            = render 'attachments/attachment', attachment: a
        h4 Comments:
        .answer_comments
          ul
            = render answer.comments
        .answer_comment_form
          = render 'comments/form', commentable: answer

        h4 Rating for Answer:
        .answer_votes
          = render 'votes/score', votable: answer
        .answer_votesbuttons 
          = render 'votes/buttons', votable: answer
        .answer_links
          - if can?(:best_answer, answer)
            -unless answer.best?
              p= link_to 'Accept as the best Answer', best_answer_path(answer), remote: true, method: :patch 
          - if can?(:modify, answer)
            p= link_to 'Delete Answer', answer, :authenticity_token => form_authenticity_token(), remote: true, method: :delete, data: { confirm: 'Are You sure?' }
            p= link_to 'Edit Answer', '', class: 'edit-answer-link', data: { answer_id: answer.id }
            p
              = form_for answer, remote: true, html: { id: "edit-answer-#{answer.id}" } do |f|
                = f.label :body, "Answer"
                .answer-edit-errors
                = f.text_area :body
                p Attachments:
                p
                  .links
                    = link_to_add_association 'Add Attachment', f, :attachments, 
                    partial: 'attachments/fields'
                p= f.submit 'Save'    

app/views/answers/_answerpub.html.slim
div id="answer-#{ answer.id }" class="answer" 
  .answer_body
    - if answer.persisted?
      - if answer.best?
        p Best Answer
      p
        h4 Anwer-#{ answer.id } 
        = answer.body
      h4 Attachments:
      ul
        - answer.attachments.each do |a|
          = render 'attachments/attachment', attachment: a
      h4 Comments:
      .answer_comments
        ul
          = render answer.comments.order(created_at: :asc)
      .answer_comment_form
        = render 'comments/form', commentable: answer

      h4 Rating for Answer:
      .answer_votes
        = render 'votes/score', votable: answer
      .answer_votesbuttons
        = render 'votes/buttons', votable: answer
      

app/views/answers/_form.html.slim
- if can?(:create, Answer)
  = form_for [@question, @answer], remote: true do |f|
    = f.label :body, 'Your Answer'
    .answer-errors
    = f.text_area :body
    p
      = f.fields_for :attachments, @answer = @question.answers.build do |attachment|
        = render 'attachments/fields', f: attachment
      .links
        = link_to_add_association 'Add Attachment', f, :attachments, 
          partial: 'attachments/fields'
    p= f.submit 'Send'
- else
  p
    | You need to sign in or sign up before create answer.

app/views/answers/best_answer.js.erb
$('.answers').html('<%= j render @question.answers %>');

app/views/answers/create.js.erb
<% if @answer.errors.present? %>
 <% @answer.errors.full_messages.each do |message| %>
    $('.answer-errors').append('<ul><li><%= j message %></li></ul>');
<% end %>
<% else %>
  <% if remotipart_submitted? %>
    $('.answers').append('<%=  j "#{ render(@answer) }" %>');
  <% else %>
    $('.answers').append('<%=  j render(@answer) %>');
  <% end %>
  $('#new_answer').find('#answer_body').val('');
  $('.nested-fields').find('#answer_attachments_attributes_0_file').val('');
  $('.answer-errors').empty();
  <% publish_to "/questions/#{@question.id}/answers" do %>
      var user_id = gon.current_user_id
      var answer_user_id = <%= @answer.user_id %>
      var answer_id = <%= @answer.id %>
      if (answer_user_id != user_id) {
        $('.answers').append('<%=  j render 'answerpub', answer: @answer %>');
        if (user_id == undefined) {
          $('#answer-' + answer_id).find('.answer_comment_form').empty()
          $('#answer-' + answer_id).find('.answer_votesbuttons').empty()
        } 
      }
  <% end %>
<% end %>
  

app/views/answers/destroy.js.erb
<% if @answer.destroyed? %>
  <% id = @answer.id %>
  $('.notice').append("<p>Your answer successfully destroyed.</p>")
  $('<%= "#answer-#{ @answer.id }" %>').remove();
<% else %>
  $('.notice').append("<p >Your can't delete answer </p>")
<% end %>

app/views/answers/edit.html.slim
p == render 'form'

app/views/answers/new.html.slim
== render 'form'

app/views/answers/update.js.erb
<% if @answer.errors.present? %>
  <% @answer.errors.full_messages.each do |message| %>
    $('.answer-edit-errors').append('<ul><li><%= j message %></li></ul>');
  <% end %>
<% else %>
  <% if remotipart_submitted? %>
    $('<%= "#answer-#{ @answer.id }" %>').replaceWith("<%= j "#{ render "answer", answer: @answer }" %>");
  <% else %>
    $('<%= "#answer-#{ @answer.id }" %>').replaceWith("<%= j render "answer", answer: @answer %>");
  <% end %>
  $('.answer-edit-errors').empty();
<% end %>